name: Build & Publish mldatascience-notebook Docker Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish Docker Image
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: mldatascience-notebook

    - name: Configure environment
      id: config
      run: |
        VERSION=`cat VERSION`
        echo ::set-output name=version::$VERSION

    - name: Publish docker
      id: docker
      uses: yjcyxky/docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mldatascience-notebook
        tag: ${{ steps.config.outputs.version }}

    - name: Print the name of built image
      run: echo "${{steps.docker.outputs.image}}"

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          # mldatascience-notebook镜像自动构建通知
          @Choppy Team 主人，我已将您刚更新在Github上的mldatascience-notebook代码，构建成Docker镜像发布到Dockerhub镜像仓库了，请您随时取用
          > Choppy Team：可登录 https://github.com/jupyter-datascience/datascience-stacks/mldatascience-notebook 查看详情
        at: Choppy Team