name: Build & Publish pydatascience-notebook

on:
  push:
    branches:    
      - master
      - dev
    paths:
      - 'pydatascience-notebook/VERSION'
      - 'pydatascience-notebook/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish Docker Image
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Configure environment
      id: config
      run: |
        VERSION=`cat VERSION`
        echo ::set-output name=version::$VERSION
      working-directory: pydatascience-notebook

    - name: Publish docker
      id: docker
      uses: yjcyxky/docker-action@master
      if: github.ref == 'refs/heads/dev'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: choppydocker/pydatascience-notebook
        tag: ${{ steps.config.outputs.version }}
        flag: test
        subdir: pydatascience-notebook

    - name: Publish docker
      id: docker
      uses: yjcyxky/docker-action@master
      if: github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: choppydocker/pydatascience-notebook
        tag: ${{ steps.config.outputs.version }}
        subdir: pydatascience-notebook

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      if: success()
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          # [SUCCESS] pydatascience-notebook镜像自动构建
          点击<a href="https://github.com/jupyter-datascience/datascience-stacks/pydatascience-notebook">pydatascience-notebook</a> 查看详情
        at: Choppy Team

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      if: failure()
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          # [FAILED] pydatascience-notebook镜像自动构建
          点击<a href="https://github.com/jupyter-datascience/datascience-stacks/pydatascience-notebook">pydatascience-notebook</a> 查看详情
        at: Choppy Team
